import { db } from '@/lib/db';
import { NextResponse } from 'next/server';

// GET /api/flows - List all flows (with mock data fallback)
export async function GET() {
  try {
    const flows = await db.flow.findMany({
      where: { deletedAt: null },
      include: { nodes: true, edges: true },
      orderBy: { updatedAt: 'desc' },
    });
    return NextResponse.json(flows);
  } catch {
    return NextResponse.json(getMockFlows());
  }
}

function getMockFlows() {
  const now = new Date();
  return [
    {
      id: 'flow-1',
      name: 'Process Data Pipeline',
      description: 'Main data collection pipeline for process values. Reads temperature, pressure, and flow data from PLC and publishes to UNS.',
      status: 'running',
      isPublished: true,
      isActive: true,
      lastRun: new Date(now.getTime() - 60000).toISOString(),
      createdAt: new Date(now.getTime() - 86400000 * 10).toISOString(),
      updatedAt: new Date(now.getTime() - 3600000).toISOString(),
      nodes: [
        {
          id: 'node-1-1',
          flowId: 'flow-1',
          type: 'modbus_read',
          label: 'Read Temperature',
          x: 100,
          y: 100,
          executionOrder: 0,
          inputs: [],
          outputs: ['output'],
          config: { address: '40001', dataType: 'FLOAT', unit: '°C' },
        },
        {
          id: 'node-1-2',
          flowId: 'flow-1',
          type: 'modbus_read',
          label: 'Read Pressure',
          x: 100,
          y: 250,
          executionOrder: 1,
          inputs: [],
          outputs: ['output'],
          config: { address: '40003', dataType: 'FLOAT', unit: 'bar' },
        },
        {
          id: 'node-1-3',
          flowId: 'flow-1',
          type: 'scale',
          label: 'Scale Values',
          x: 300,
          y: 175,
          executionOrder: 2,
          inputs: ['input-1', 'input-2'],
          outputs: ['output'],
          config: { operations: [{ tag: 'temperature', scale: 0.1 }, { tag: 'pressure', scale: 0.01 }] },
        },
        {
          id: 'node-1-4',
          flowId: 'flow-1',
          type: 'filter',
          label: 'Quality Check',
          x: 500,
          y: 175,
          executionOrder: 3,
          inputs: ['input', 'log'],
          outputs: ['output', 'rejected'],
          config: { rejectBadQuality: true, logRejections: true },
        },
        {
          id: 'node-1-5',
          flowId: 'flow-1',
          type: 'mqtt_publish',
          label: 'Publish to UNS',
          x: 700,
          y: 175,
          executionOrder: 4,
          inputs: ['input', 'dead-letter'],
          outputs: [],
          config: { topic: 'ia/factory1/line1/', qos: 1, retain: true },
        },
      ],
      edges: [
        { id: 'edge-1-1', flowId: 'flow-1', source: 'node-1-1', sourceHandle: 'output', target: 'node-1-3', targetHandle: 'input-1' },
        { id: 'edge-1-2', flowId: 'flow-1', source: 'node-1-2', sourceHandle: 'output', target: 'node-1-3', targetHandle: 'input-2' },
        { id: 'edge-1-3', flowId: 'flow-1', source: 'node-1-3', sourceHandle: 'output', target: 'node-1-4', targetHandle: 'input' },
        { id: 'edge-1-4', flowId: 'flow-1', source: 'node-1-4', sourceHandle: 'output', target: 'node-1-5', targetHandle: 'input' },
        { id: 'edge-1-5', flowId: 'flow-1', source: 'node-1-4', sourceHandle: 'rejected', target: 'node-1-5', targetHandle: 'dead-letter' },
        { id: 'edge-1-6', flowId: 'flow-1', source: 'node-1-3', sourceHandle: 'error', target: 'node-1-4', targetHandle: 'log' },
      ],
    },
    {
      id: 'flow-2',
      name: 'Alarm Processing',
      description: 'Processes alarm conditions, applies deadband filtering, and routes notifications through the appropriate channels.',
      status: 'running',
      isPublished: true,
      isActive: true,
      lastRun: new Date(now.getTime() - 30000).toISOString(),
      createdAt: new Date(now.getTime() - 86400000 * 8).toISOString(),
      updatedAt: new Date(now.getTime() - 7200000).toISOString(),
      nodes: [
        {
          id: 'node-2-1',
          flowId: 'flow-2',
          type: 'tag_subscribe',
          label: 'Subscribe Tags',
          x: 100,
          y: 150,
          executionOrder: 0,
          inputs: [],
          outputs: ['output'],
          config: { tags: ['temperature', 'pressure', 'vibration', 'motor_speed'] },
        },
        {
          id: 'node-2-2',
          flowId: 'flow-2',
          type: 'alarm_eval',
          label: 'Evaluate Conditions',
          x: 300,
          y: 150,
          executionOrder: 1,
          inputs: ['input'],
          outputs: ['triggered', 'normal'],
          config: { deadband: { temperature: 0.5, pressure: 0.1 }, delay: 5000 },
        },
        {
          id: 'node-2-3',
          flowId: 'flow-2',
          type: 'severity_classify',
          label: 'Classify Severity',
          x: 500,
          y: 150,
          executionOrder: 2,
          inputs: ['input'],
          outputs: ['output'],
          config: { levels: { critical: 90, warning: 75, info: 60 } },
        },
        {
          id: 'node-2-4',
          flowId: 'flow-2',
          type: 'notify',
          label: 'Send Notifications',
          x: 700,
          y: 150,
          executionOrder: 3,
          inputs: ['input', 'clear'],
          outputs: [],
          config: { channels: ['email', 'websocket'], escalateAfter: 300000 },
        },
      ],
      edges: [
        { id: 'edge-2-1', flowId: 'flow-2', source: 'node-2-1', sourceHandle: 'output', target: 'node-2-2', targetHandle: 'input' },
        { id: 'edge-2-2', flowId: 'flow-2', source: 'node-2-2', sourceHandle: 'triggered', target: 'node-2-3', targetHandle: 'input' },
        { id: 'edge-2-3', flowId: 'flow-2', source: 'node-2-3', sourceHandle: 'output', target: 'node-2-4', targetHandle: 'input' },
        { id: 'edge-2-4', flowId: 'flow-2', source: 'node-2-2', sourceHandle: 'normal', target: 'node-2-4', targetHandle: 'clear' },
      ],
    },
    {
      id: 'flow-3',
      name: 'Data Aggregation',
      description: 'Aggregates tag values into 1-minute averages for historical trending and reporting. Stores results in time-series format.',
      status: 'stopped',
      isPublished: true,
      isActive: true,
      lastRun: new Date(now.getTime() - 86400000).toISOString(),
      createdAt: new Date(now.getTime() - 86400000 * 5).toISOString(),
      updatedAt: new Date(now.getTime() - 86400000).toISOString(),
      nodes: [
        {
          id: 'node-3-1',
          flowId: 'flow-3',
          type: 'buffer',
          label: 'Time Buffer',
          x: 100,
          y: 150,
          executionOrder: 0,
          inputs: ['input'],
          outputs: ['output'],
          config: { windowMs: 60000, maxSize: 1000 },
        },
        {
          id: 'node-3-2',
          flowId: 'flow-3',
          type: 'aggregate',
          label: 'Calculate Averages',
          x: 300,
          y: 150,
          executionOrder: 1,
          inputs: ['input'],
          outputs: ['output'],
          config: { functions: ['avg', 'min', 'max', 'count'], groupBy: 'tag' },
        },
        {
          id: 'node-3-3',
          flowId: 'flow-3',
          type: 'store',
          label: 'Store Results',
          x: 500,
          y: 150,
          executionOrder: 2,
          inputs: ['input'],
          outputs: [],
          config: { retentionDays: 90, compress: true },
        },
      ],
      edges: [
        { id: 'edge-3-1', flowId: 'flow-3', source: 'node-3-1', sourceHandle: 'output', target: 'node-3-2', targetHandle: 'input' },
        { id: 'edge-3-2', flowId: 'flow-3', source: 'node-3-2', sourceHandle: 'output', target: 'node-3-3', targetHandle: 'input' },
      ],
    },
  ];
}
